# Generated by Django 4.0.4 on 2022-05-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0003_rename_recommended_mobile_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
