# Generated by Django 4.0.4 on 2022-05-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0004_mobile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
