# Generated by Django 4.0.4 on 2022-05-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0006_company_alter_mobile_make_alter_mobile_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='make',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
