# Generated by Django 4.0.4 on 2022-05-21 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0007_alter_mobile_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_store.company'),
        ),
    ]
