# Generated by Django 4.0.4 on 2022-05-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0009_alter_mobile_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Icons8_flat_cell_phone.svg/768px-Icons8_flat_cell_phone.svg.png'),
        ),
    ]
