# Generated by Django 4.0.4 on 2022-05-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0011_country_mobile_released_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='released_countries',
            field=models.ManyToManyField(related_name='Countries', to='mobile_store.country'),
        ),
    ]
